###服务启动端口号
server:
  port: 8753
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-itmayiedu-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

    ###把自己注册到eureka中去
    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true
  ###注册真实的ip
  ##instance:
   ## prefer-ip-address: true
    ##instance-id: 127.0.0.1
